import {useMutation,useQuery,useQueryClient}from"@tanstack/react-query";import * as api from"@/lib/jobs";
const clear=(q:ReturnType<typeof useQueryClient>)=>Promise.all([q.invalidateQueries({queryKey:["jobs"]}),q.invalidateQueries({queryKey:["job"]})]);
export const useJobs=(f:api.JobFilters={})=>useQuery({queryKey:["jobs",f],queryFn:()=>api.browseJobs(f)});
export const useJobCategories=(enabled=true)=>useQuery({queryKey:["jobs","categories"],queryFn:async()=>{try{return await api.jobCategories()}catch(error){console.error("Job category query failed",error);throw error}},staleTime:300000,enabled});
export const useJob=(id:string)=>useQuery({queryKey:["job",id],queryFn:()=>api.getJob(id),enabled:!!id});
export const useMyJobs=()=>useQuery({queryKey:["jobs","mine"],queryFn:api.myJobs});export const useSavedJobs=()=>useQuery({queryKey:["jobs","saved"],queryFn:api.savedJobs});
export const useMyApplications=()=>useQuery({queryKey:["jobs","applications"],queryFn:api.myApplications});export const useJobApplications=(id:string)=>useQuery({queryKey:["jobs","applications",id],queryFn:()=>api.jobApplications(id),enabled:!!id});
export const useMySeekerProfile=()=>useQuery({queryKey:["jobs","profile"],queryFn:api.mySeekerProfile});export const useWorkers=(f:api.WorkerFilters={})=>useQuery({queryKey:["jobs","workers",f],queryFn:()=>api.findWorkers(f)});export const useWorker=(id:string)=>useQuery({queryKey:["jobs","worker",id],queryFn:()=>api.getWorker(id),enabled:!!id});
export const usePendingJobs=()=>useQuery({queryKey:["jobs","pending"],queryFn:api.pendingJobs});
export const useEmployerContact=(id:string)=>useQuery({queryKey:["jobs","employer-contact",id],queryFn:()=>api.getEmployerContact(id),enabled:!!id});export const useSeekerContact=(id:string)=>useQuery({queryKey:["jobs","seeker-contact",id],queryFn:()=>api.getSeekerContact(id),enabled:!!id});
export function useJobMutation(){const q=useQueryClient();return useMutation({mutationFn:async(v:{type:"save"|"submit"|"submit-profile"|"status"|"delete"|"favorite"|"report"|"block"|"apply"|"application-status"|"profile"|"worker-report"|"invite"|"settings"|"moderate";id?:string;value?:any})=>{if(v.type==="save")return api.saveJob(v.value,v.id);if(v.type==="submit")return api.submitJob(v.id!);if(v.type==="submit-profile")return api.submitSeekerProfile(v.id!);if(v.type==="status")return api.setJobStatus(v.id!,v.value);if(v.type==="delete")return api.deleteJob(v.id!);if(v.type==="favorite")return api.saveJobFavorite(v.id!,v.value);if(v.type==="report")return api.reportJob(v.id!,v.value.reason,v.value.details);if(v.type==="worker-report")return api.reportWorker(v.id!,v.value);if(v.type==="block")return api.blockUser(v.id!,v.value);if(v.type==="apply")return api.applyForJob(v.value);if(v.type==="application-status")return api.setApplicationStatus(v.id!,v.value);if(v.type==="invite")return api.inviteWorker(v.value.job_id,v.id!,v.value.message);if(v.type==="settings")return api.saveNotificationSettings(v.value);if(v.type==="moderate")return api.moderateJob(v.id!,v.value);return api.saveSeekerProfile(v.value)},onSuccess:()=>{clear(q);q.invalidateQueries({queryKey:["jobs","profile"]});q.invalidateQueries({queryKey:["jobs","applications"]})}})}