import {useMutation,useQuery,useQueryClient}from"@tanstack/react-query";import * as api from"@/lib/jobs";
const clear=(q:ReturnType<typeof useQueryClient>)=>Promise.all([q.invalidateQueries({queryKey:["jobs"]}),q.invalidateQueries({queryKey:["job"]}),q.invalidateQueries({queryKey:["jobs","owner"]}),q.invalidateQueries({queryKey:["jobs","mine"]}),q.invalidateQueries({queryKey:["jobs","saved"]}),q.invalidateQueries({queryKey:["jobs","pending"]}),q.invalidateQueries({queryKey:["jobs","applications"]}),q.invalidateQueries({queryKey:["jobs","workers"]}),q.invalidateQueries({queryKey:["jobs","worker"]}),q.invalidateQueries({queryKey:["jobs","profile"]})]);
export const useJobs=(f:api.JobFilters={})=>useQuery({queryKey:["jobs",f],queryFn:()=>api.browseJobs(f)});
export const useJobCategories=(enabled=true)=>useQuery({queryKey:["jobs","categories"],queryFn:async()=>{try{return await api.jobCategories()}catch(error){console.error("Job category query failed",error);throw error}},staleTime:300000,enabled});
export const useJob=(id:string)=>useQuery({queryKey:["job",id],queryFn:()=>api.getJob(id),enabled:!!id});
export const useOwnerJob=(id:string,enabled=true)=>useQuery({queryKey:["jobs","owner",id],queryFn:()=>api.getOwnerJob(id),enabled:!!id&&enabled});
export const useMyJobs=(enabled=true)=>useQuery({queryKey:["jobs","mine"],queryFn:api.myJobs,enabled});export const useSavedJobs=()=>useQuery({queryKey:["jobs","saved"],queryFn:api.savedJobs});
export const useMyApplications=()=>useQuery({queryKey:["jobs","applications"],queryFn:api.myApplications});export const useJobApplications=(id:string)=>useQuery({queryKey:["jobs","applications",id],queryFn:()=>api.jobApplications(id),enabled:!!id});
export const useMySeekerProfile=(enabled=true)=>useQuery({queryKey:["jobs","profile"],queryFn:api.mySeekerProfile,enabled});export const useWorkers=(f:api.WorkerFilters={})=>useQuery({queryKey:["jobs","workers",f],queryFn:()=>api.findWorkers(f)});export const useWorker=(id:string)=>useQuery({queryKey:["jobs","worker",id],queryFn:()=>api.getWorker(id),enabled:!!id});
export const usePendingJobs=()=>useQuery({queryKey:["jobs","pending"],queryFn:api.pendingJobs});
export const useEmployerContact=(id:string)=>useQuery({queryKey:["jobs","employer-contact",id],queryFn:()=>api.getEmployerContact(id),enabled:!!id});
export function useJobMutation(){const q=useQueryClient();return useMutation({mutationFn:async(v:{type:"save"|"submit"|"submit-profile"|"status"|"delete"|"favorite"|"report"|"block"|"apply"|"application-status"|"profile"|"worker-report"|"invite"|"settings"|"moderate";id?:string;value?:any})=>{if(v.type==="save")return api.saveJob(v.value,v.id);if(v.type==="submit")return api.submitJob(v.id!);if(v.type==="submit-profile")return api.submitSeekerProfile(v.id!);if(v.type==="status")return api.setJobStatus(v.id!,v.value);if(v.type==="delete")return api.deleteJob(v.id!);if(v.type==="favorite")return api.saveJobFavorite(v.id!,v.value);if(v.type==="report")return api.reportJob(v.id!,v.value.reason,v.value.details);if(v.type==="worker-report")return api.reportWorker(v.id!,v.value);if(v.type==="block")return api.blockUser(v.id!,v.value);if(v.type==="apply")return api.applyForJob(v.value);if(v.type==="application-status")return api.setApplicationStatus(v.id!,v.value);if(v.type==="invite")return api.inviteWorker(v.value.job_id,v.id!,v.value.message);if(v.type==="settings")return api.saveNotificationSettings(v.value);if(v.type==="moderate")return api.moderateJob(v.id!,v.value);return api.saveSeekerProfile(v.value)},onSuccess:async(_,variables)=>{await clear(q);if(variables.id)await q.invalidateQueries({queryKey:["jobs","employer-contact",variables.id]})}})}