import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import * as api from "@/lib/offerings";

const invalidate = (q: ReturnType<typeof useQueryClient>) => q.invalidateQueries({ queryKey: ["offerings"] });
export const useOfferings = (filters: api.OfferingFilters = {}) => useQuery({ queryKey: ["offerings", filters], queryFn: () => api.browseOfferings(filters) });
export const useOffering = (id: string) => useQuery({ queryKey: ["offering", id], queryFn: () => api.getOffering(id), enabled: !!id });
export const useMyOfferings = () => useQuery({ queryKey: ["offerings", "mine"], queryFn: api.myOfferings });
export const useSavedOfferings = () => useQuery({ queryKey: ["offerings", "saved"], queryFn: api.savedOfferings });
export function useSaveOffering(id?: string) { const q = useQueryClient(); return useMutation({ mutationFn: (input: api.OfferingInput) => api.saveOffering(input, id), onSuccess: () => { invalidate(q); q.invalidateQueries({ queryKey: ["offering", id] }); } }); }
export function useOfferingAction() { const q = useQueryClient(); return useMutation({ mutationFn: async ({ type, id, value, reason }: { type: "delete" | "submit" | "enable" | "favorite" | "block" | "review" | "report" | "moderate" | "resolve-report"; id: string; value?: any; reason?: string }) => { if (type === "delete") return api.deleteOffering(id); if (type === "submit") return api.submitOffering(id); if (type === "enable") return api.setOfferingEnabled(id, !!value); if (type === "favorite") return api.offeringFavorite(id, !!value); if (type === "block") return api.offeringBlock(id, !!value); if (type === "review") return api.offeringReview(id, value.rating, value.body); if (type === "report") return api.offeringReport(id, value, reason); if (type === "resolve-report") return api.resolveOfferingReport(id); return api.moderateOffering(id, value, reason); }, onSuccess: (_, vars) => { invalidate(q); q.invalidateQueries({ queryKey: ["offering", vars.id] }); q.invalidateQueries({ queryKey: ["offerings", "saved"] }); } }); }
export function useOfferingPhoto() { const q = useQueryClient(); return useMutation({ mutationFn: ({ offeringId, filename, file, contentType, altText }: { offeringId: string; filename: string; file: Blob; contentType: "image/jpeg"|"image/png"|"image/webp"; altText?: string }) => api.uploadOfferingPhoto(offeringId, filename, file, contentType, altText), onSuccess: (_, v) => q.invalidateQueries({ queryKey: ["offering", v.offeringId] }) }); }
export function useDeleteOfferingPhoto() { const q = useQueryClient(); return useMutation({ mutationFn: (photo: { id: string; storage_path: string; offering_id: string }) => api.deleteOfferingPhoto(photo), onSuccess: (_, p) => q.invalidateQueries({ queryKey: ["offering", p.offering_id] }) }); }
export const useOfferingAdminQueue = (enabled: boolean) => useQuery({ queryKey: ["offerings", "admin"], queryFn: api.adminOfferingQueue, enabled });