begin;
drop policy if exists "job private media anon owner uploads" on storage.objects;
drop policy if exists "job private media anon owner reads" on storage.objects;
drop policy if exists "job private media anon owner deletes" on storage.objects;
drop function if exists public.job_storage_seeker_owner(uuid);
drop function if exists public.job_storage_seeker_upload_allowed(uuid);
drop function if exists public.job_storage_application_owner(uuid);
drop function if exists public.job_storage_application_upload_allowed(uuid);
revoke execute on function public.job_submit(uuid),public.job_submit_seeker_profile(uuid),public.job_set_status(uuid,public.job_status),public.job_set_application_status(uuid,public.job_application_status),public.job_upsert_employer_contact(uuid,text,text,text,text,boolean,boolean,boolean),public.job_upsert_seeker_contact(uuid,text,text,text,boolean,boolean,boolean),public.job_save(uuid),public.job_block_user(text),public.job_invite_worker(uuid,uuid,text),public.job_get_employer_contact(uuid),public.job_prepare_application_resume(uuid,text),public.job_attach_application_resume(uuid,text),public.job_prepare_seeker_photo(uuid,text),public.job_attach_seeker_photo(uuid,text) from anon;
drop function if exists public.job_save_draft(jsonb,uuid,jsonb);
drop function if exists public.job_save_seeker_profile(jsonb,jsonb);
drop function if exists public.job_apply(jsonb);
drop function if exists public.job_delete_draft(uuid);
drop function if exists public.job_get_my_jobs();
drop function if exists public.job_get_owner_job(uuid);
drop function if exists public.job_get_my_seeker_profile();
drop function if exists public.job_get_my_applications();
drop function if exists public.job_get_job_applications(uuid);
drop function if exists public.job_remove_saved(uuid);
drop function if exists public.job_unblock_user(text);
drop function if exists public.job_save_notification_settings(jsonb);
drop function if exists public.job_report(uuid,public.job_report_reason,text);
drop function if exists public.job_report_profile(uuid,public.job_report_reason,text);
commit;