import React,{useEffect,useState}from"react";
import{ActivityIndicator,FlatList,Pressable,ScrollView,StyleSheet,Text,TextInput,View}from"react-native";
import{useRouter}from"expo-router";
import colors from"@/constants/colors";
import{useOfferingCategories,useOfferings}from"@/hooks/useOfferings";
import{useSupabaseAuth}from"@/hooks/useBusiness";

export default function Offerings(){
  const auth=useSupabaseAuth();const r=useRouter();const[q,setQ]=useState("");const[k,setK]=useState<"product"|"service">("product");const[category,setCategory]=useState<string>();
  const categories=useOfferingCategories(k,auth.ready);const{data,isLoading,error,refetch}=useOfferings({query:q,kind:k,category});
  useEffect(()=>{if(categories.error)console.error("Offering category loading failed",categories.error)},[categories.error]);
  useEffect(()=>{setCategory(undefined)},[k]);
  return <View style={s.root}><Text style={s.title}>Products & Services</Text>
    <View style={s.row}><TextInput style={s.input} value={q} onChangeText={setQ} placeholder="Search name or description" placeholderTextColor={colors.light.mutedForeground}/>{(["product","service"]as const).map(x=><Pressable key={x} style={[s.pill,k===x&&s.active]} onPress={()=>setK(x)}><Text style={s.t}>{x}</Text></Pressable>)}</View>
    <Text style={s.label}>Category</Text>
    {categories.isLoading?<ActivityIndicator color={colors.light.primary}/>:categories.error?<View><Text style={s.error}>Unable to load categories. Please try again.</Text><Pressable style={s.retry} onPress={()=>void categories.refetch()}><Text style={s.t}>RETRY CATEGORIES</Text></Pressable></View>:<ScrollView horizontal style={s.categoryScroll} showsHorizontalScrollIndicator={false} contentContainerStyle={s.categories}><Pressable style={[s.pill,!category&&s.active]} onPress={()=>setCategory(undefined)}><Text style={s.t}>All</Text></Pressable>{(categories.data??[]).filter(x=>!x.parent_id).map(x=><Pressable key={x.id} style={[s.pill,category===x.name&&s.active]} onPress={()=>setCategory(x.name)}><Text style={s.t}>{x.name}</Text></Pressable>)}</ScrollView>}
    {isLoading?<ActivityIndicator color={colors.light.primary}/>:error?<View><Text style={s.error}>Unable to load listings. Please try again.</Text><Pressable style={s.retry} onPress={()=>void refetch()}><Text style={s.t}>RETRY</Text></Pressable></View>:<FlatList data={data??[]} keyExtractor={x=>x.id} contentContainerStyle={s.list} ListEmptyComponent={<Text style={s.empty}>No approved listings match these filters.</Text>} renderItem={({item})=><Pressable testID="open-offering" style={s.card} onPress={()=>r.push(`/business/offering/${item.id}` as any)}><Text style={s.name}>{item.name}</Text><Text style={s.meta}>{item.kind.toUpperCase()} · {item.category}{item.subcategory?` / ${item.subcategory}`:""} · {item.city}</Text><Text style={s.meta}>{item.price==null?"Contact for price":`${item.price} ${item.price_unit}`}</Text></Pressable>}/>}
  </View>
}
const s=StyleSheet.create({root:{flex:1,backgroundColor:colors.light.background,padding:20},title:{color:colors.light.foreground,fontSize:25,fontWeight:"900",marginBottom:16},row:{flexDirection:"row",gap:8,marginBottom:16},input:{flex:1,backgroundColor:colors.light.card,color:colors.light.foreground,borderRadius:10,padding:12},label:{color:colors.light.foreground,fontWeight:"800"},categoryScroll:{flexGrow:0,maxHeight:58},categories:{gap:8,paddingVertical:10},pill:{padding:10,backgroundColor:colors.light.card,borderRadius:10},active:{backgroundColor:colors.light.primary},t:{color:colors.light.foreground,fontSize:11,fontWeight:"700"},list:{gap:10,paddingTop:10},card:{backgroundColor:colors.light.card,borderRadius:14,borderWidth:1,borderColor:colors.light.border,padding:15},name:{color:colors.light.foreground,fontWeight:"800",fontSize:16},meta:{color:colors.light.mutedForeground,fontSize:12,marginTop:5},empty:{color:colors.light.mutedForeground,textAlign:"center",marginTop:50},error:{color:colors.light.destructive,textAlign:"center",marginVertical:12},retry:{alignSelf:"center",backgroundColor:colors.light.primary,padding:10,borderRadius:10}});