import React,{useEffect,useState}from"react";
import{ActivityIndicator,Alert,Linking,ScrollView,Text,TextInput,View}from"react-native";
import{useLocalSearchParams,useRouter}from"expo-router";
import{useSupabaseAuth}from"@/hooks/useBusiness";
import{useEmployerContact,useJob,useJobMutation}from"@/hooks/useJobs";
import{isUserBlocked}from"@/lib/jobs";
import{Button,styles as s}from"@/components/JobsUi";
import{copyLink,shareLink}from"@/lib/share";
const reportReasons=["fake_job","scam","misleading_information","spam","inappropriate_content","illegal_activity","discrimination","harassment","other"]as const;
export default function JobDetail(){useSupabaseAuth();const{id}=useLocalSearchParams<{id:string}>();const r=useRouter();const{data:j,isLoading,error}=useJob(id);const{data:contact}=useEmployerContact(id);const m=useJobMutation();const[reporting,setReporting]=useState(false);const[reason,setReason]=useState<typeof reportReasons[number]>("other");const[details,setDetails]=useState("");const[blocked,setBlocked]=useState(false);useEffect(()=>{if(!j?.employer_id)return;void isUserBlocked(j.employer_id).then(setBlocked).catch(e=>console.error("Could not load employer block state",e));},[j?.employer_id]);
if(isLoading)return <View style={s.root}><ActivityIndicator/></View>;if(!j)return <View style={s.root}><Text style={s.empty}>{error?(error as Error).message:"Job unavailable"}</Text></View>;
const open=(url:string)=>void Linking.openURL(url).catch(()=>Alert.alert("Unavailable","No compatible app is available."));
const submitReport=()=>{if(!details.trim())return Alert.alert("Add report details","Describe the issue so our team can review it.");m.mutate({type:"report",id:j.id,value:{reason,details:details.trim()}},{onSuccess:()=>{setReporting(false);setDetails("");Alert.alert("Report submitted","Thank you for helping keep hiring safe.");},onError:(e:Error)=>Alert.alert("Could not report",e.message)});};
const changeBlock=()=>{if(!j.employer_id)return;const action=blocked?"Unblock":"Block";Alert.alert(`${action} employer?`,blocked?"This removes your block on the employer.":"This blocks the employer and closes this job detail.",[{text:"Cancel",style:"cancel"},{text:action,style:blocked?"default":"destructive",onPress:()=>m.mutate({type:"block",id:j.employer_id,value:!blocked},{onSuccess:()=>{if(blocked){setBlocked(false);Alert.alert("Employer unblocked","Your block was removed.");return}Alert.alert("Employer blocked","Returning to job discovery.",[{text:"OK",onPress:()=>r.replace("/business/jobs/discover" as any)}]);},onError:(e:Error)=>Alert.alert(`Could not ${action.toLowerCase()} employer`,e.message)})}])};
const link=`gamezone-arena://jobs/${j.id}`;
return <ScrollView style={s.root} contentContainerStyle={s.content}><Text style={s.back} onPress={()=>r.back()}>← Back</Text><Text style={s.title}>{j.title}</Text><Text style={s.company}>{j.company_name}</Text><Text style={s.subtitle}>{j.description}</Text>{[["Responsibilities",j.responsibilities],["Skills",j.required_skills.join(", ")],["Experience",j.required_experience_months==null?null:`${j.required_experience_months} months`],["Education",j.education_requirement],["Location",[j.location_text,j.area,j.city].filter(Boolean).join(", ")],["Working hours",j.working_hours],["Benefits",j.benefits],["Deadline",j.application_deadline]].filter((x):x is [string,string]=>!!x[1]).map(x=><View key={x[0]} style={s.card}><Text style={s.name}>{x[0]}</Text><Text style={s.meta}>{x[1]}</Text></View>)}<View style={s.row}><Button label="Apply now" kind onPress={()=>r.push(`/business/jobs/apply?jobId=${j.id}` as any)}/><Button label="Save" onPress={()=>m.mutate({type:"favorite",id:j.id,value:true},{onSuccess:()=>Alert.alert("Saved","Job saved."),onError:(e:Error)=>Alert.alert("Could not save",e.message)})}/><Button label="Share" onPress={()=>void shareLink(j.title,`${j.title}: ${link}`)}/><Button label="Copy link" onPress={()=>void copyLink(link).then(()=>Alert.alert("Copied","Job link copied."))}/>{contact?.phone&&<Button label="Call" onPress={()=>open(`tel:${contact.phone!.replace(/[ ()-]/g,"")}`)}/>} {contact?.whatsapp&&<Button label="WhatsApp" onPress={()=>open(`https://wa.me/${contact.whatsapp!.replace(/\D/g,"")}`)}/>}<Button label="Map" onPress={()=>open(`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(j.location_text||`${j.area||""} ${j.city}`)}`)}/><Button label={reporting?"Cancel report":"Report"} onPress={()=>setReporting(x=>!x)}/>{j.employer_id?<Button label={blocked?"Unblock employer":"Block employer"} onPress={changeBlock}/>:null}</View>{reporting&&<View style={s.card}><Text style={s.name}>Report this job</Text><Text style={s.meta}>Choose a reason and add details for the review team.</Text><View style={s.row}>{reportReasons.map(x=><Button key={x} label={x.replaceAll("_"," ")} kind={reason===x} onPress={()=>setReason(x)}/>)}</View><TextInput style={s.input} value={details} onChangeText={setDetails} placeholder="What happened?" placeholderTextColor={s.subtitle.color} multiline maxLength={2000}/><Button kind label={m.isPending?"Submitting…":"Submit report"} onPress={submitReport}/></View>}</ScrollView>}