import React,{useEffect,useState}from"react";
import{Alert,Image,ScrollView,Text,TextInput}from"react-native";
import * as DocumentPicker from"expo-document-picker";
import{useLocalSearchParams,useRouter}from"expo-router";
import{useSupabaseAuth}from"@/hooks/useBusiness";
import{useJobMutation,useMySeekerProfile}from"@/hooks/useJobs";
import{uploadApplicationResume}from"@/lib/jobs";
import{Button,styles as s}from"@/components/JobsUi";

export default function Apply(){
  useSupabaseAuth();const{jobId}=useLocalSearchParams<{jobId:string}>();const r=useRouter();const p=useMySeekerProfile();const m=useJobMutation();
  const[f,setF]=useState({applicant_name:"",phone:"",email:"",experience:"",skills:"",introduction:"",message:""});
  const[resume,setResume]=useState<DocumentPicker.DocumentPickerAsset|null>(null);
  const[applicationId,setApplicationId]=useState<string|null>(null);const[uploading,setUploading]=useState(false);const[resumeError,setResumeError]=useState("");
  useEffect(()=>{const x=p.data;if(x)setF(v=>({...v,applicant_name:x.display_name,experience:x.experience_months==null?"":String(x.experience_months),skills:x.skills.join(", "),introduction:x.bio??""}))},[p.data]);
  const input=(k:keyof typeof f,label:string)=><TextInput style={s.input} value={f[k]} onChangeText={v=>setF({...f,[k]:v})} placeholder={label} placeholderTextColor={s.subtitle.color} multiline={k==="introduction"||k==="message"}/>;
  const chooseResume=async()=>{try{const result=await DocumentPicker.getDocumentAsync({type:["image/jpeg","image/png","image/webp","application/pdf","application/vnd.openxmlformats-officedocument.wordprocessingml.document"],copyToCacheDirectory:true});if(result.canceled)return;const asset=result.assets[0];const ext=asset.name.split(".").pop()?.toLowerCase();const types:Record<string,string>={jpg:"image/jpeg",jpeg:"image/jpeg",png:"image/png",webp:"image/webp",pdf:"application/pdf",docx:"application/vnd.openxmlformats-officedocument.wordprocessingml.document"};if(!ext||!types[ext]||asset.mimeType&&asset.mimeType!==types[ext])throw Error("Only JPG, PNG, WebP, PDF, and DOCX resumes are supported.");if(asset.size!=null&&(asset.size<=0||asset.size>5*1024*1024))throw Error("Use a resume up to 5 MB.");setResume({...asset,mimeType:asset.mimeType??types[ext]});setResumeError("")}catch(error){Alert.alert("Unable to select resume",error instanceof Error?error.message:"Please try again.")}};
  const finish=()=>{Alert.alert("Applied","Your application was sent.");r.replace("/business/jobs/applications"as any)};
  const uploadResume=async(id:string)=>{if(!resume)return finish();setUploading(true);setResumeError("");try{const blob=await(await fetch(resume.uri)).blob();await uploadApplicationResume(id,resume.name||resume.uri.split("/").pop()||"resume.pdf",blob,resume.mimeType||"application/pdf");finish()}catch(error){console.error("Resume upload failed",error);setResumeError(error instanceof Error?error.message:"Resume upload failed. Please retry.");Alert.alert("Application sent, resume upload failed","Your application was sent, but the resume was not uploaded. Retry the resume upload before leaving this screen.")}finally{setUploading(false)}};
  const submit=()=>{if(applicationId)return void uploadResume(applicationId);const months=f.experience===""?null:Number(f.experience);if(!jobId||!f.applicant_name.trim()||!f.phone.trim()||months!==null&&(!Number.isInteger(months)||months<0))return Alert.alert("Check application","Enter a name, valid phone number, and whole-number experience.");m.mutate({type:"apply",value:{job_id:jobId,applicant_name:f.applicant_name,phone:f.phone,email:f.email||null,experience_months:months,skills:f.skills.split(",").map(x=>x.trim()).filter(Boolean),introduction:f.introduction||null,message:f.message||null}},{onSuccess:application=>{setApplicationId((application as any).id);void uploadResume((application as any).id)},onError:(e:Error)=>{console.error("Application failed",e);Alert.alert("Could not apply",e.message)}})};
  const preview=resume?.mimeType?.startsWith("image/");
  return <ScrollView style={s.root} contentContainerStyle={s.content}><Text style={s.title}>Apply for job</Text><Text style={s.subtitle}>Your contact details are shared only with this job’s employer. Resume upload supports JPG, PNG, WebP, PDF, or DOCX files up to 5 MB.</Text>{resumeError?<Text style={{color:"#ef4444",fontWeight:"700"}}>{resumeError}</Text>:null}{input("applicant_name","Your name")}{input("phone","Phone")}{input("email","Email (optional)")}{input("experience","Experience in months")}{input("skills","Skills (comma separated)")}{input("introduction","Short introduction")}<Button label={resume?"Replace resume/CV":"Add resume/CV (optional)"} onPress={()=>void chooseResume()}/>{resume?<>{preview?<Image source={{uri:resume.uri}} style={{width:120,height:90,resizeMode:"contain",alignSelf:"center"}}/>:null}<Text style={s.meta}>{resume.name||"Selected resume"}</Text><Button label="Remove selected resume" onPress={()=>{setResume(null);setResumeError("")}}/></>:null}{input("message","Additional message")}<Button kind label={m.isPending?"Submitting…":uploading?"Uploading resume…":applicationId?"Retry resume upload":"Submit application"} onPress={submit}/></ScrollView>
}